### ISSUE TITLE
diagonal shift problem

### ISSUE THREAD

**Issue by Samsik2** [0x384c0/MouseToJoystickYuzu#1]
The basic four-way motion works well.

However, Diablo 3 requires 12 directions of operation.

By default, when you change the setting, only four directions are moved and the diagonal direction is not moving well.

It will only operate when the equipment is selected, can you operate the 12 directions delicately?

**Comment by 0x384c0** [comment]
It looks like similar functionality [implemented in yuzu](https://github.com/yuzu-emu/yuzu/pull/5869). This repository is no longer needed.
