### ISSUE TITLE
The legend of zelda link awaking control need help please

### ISSUE THREAD

**Issue by gamersalpha** [0x384c0/MouseToJoystickYuzu#2]
![image](https://user-images.githubusercontent.com/32466950/98287644-ea8b6180-1fa5-11eb-9527-ded7a025b286.png)

**Comment by 0x384c0** [comment]
It looks like similar functionality [implemented in yuzu](https://github.com/yuzu-emu/yuzu/pull/5869). This repository is no longer needed.
